#!/bin/bash
N=1
for NBR in "EMU1-NAME" "EMU2-NAME" "EMU3-NAME" "EMU4-NAME"
do
NAME=$(grep -w "${NBR}" gui.cfg | cut -c 11-)
if test -z $NAME
        then break
        fi
export EMU$N=$NAME
let N=$N+1
done
#echo "EMU1" "EMU2" "EMU3" "EMU4"

dialog  --no-cancel --no-ok --menu "Choix de l'EMULATEUR" 10 30 4 1 "$EMU1" 2 "$EMU2"\
 3 "$EMU3" 4 "$EMU4" 2>dialog.tmp
P=$(cat dialog.tmp)

function romlist()
{
R=$(grep ROMPATH$P gui.cfg |cut -c 10-)

ls --format single-column $R
}
romlist $P >romlist.tmp
clean()
{
cln=$(grep -w 'zip\|gba$' romlist.tmp)
echo  "$cln"
}

clean >clean.tmp
compte()
{
compte=$(grep -w 'zip\|gba$' clean.tmp |wc -l)
echo $compte

}

showline()
{
nl=$(head --lines=1 clean.tmp)
echo $nl
}
t=1
c=`compte`
while [ $c -ge 1 ] || break
do 
 tail=$(tail --lines="$c" clean.tmp)  ;echo -e "$tail \r" 1>clean.tmp
 item=`showline`
  echo  $t $item  1>>array.tmp

 let "c=$c-1"
 let "t=$t+1"

done
array()
{ 
cat array.tmp
}
list=$(cat array.tmp)
echo $list
dialog --clear
dialog  --no-cancel --no-ok --menu "Choix de la rom" 20 50 10 $list 2>dialog.tmp

rm romlist.tmp clean.tmp array.tmp
