#!/bin/bash
# Version 0.7
#memo index  boutons start et select dans jstest ne pas decommenter
#START=6
#SELECT=4
#memo index axes verticaux et horizontaux dans jstest  ne pas decommenter
#VERTICAL=1
#HORIZONTAL=0
#GRAB='number 1, value -32767'
#jstest --event /dev/input/js0 >grab.txt
while test $$ -gt 0 
do 
for GRAB in "number 0, value -32767" "number 0, value 32767" \ #axehorizontal
"number 4, value 1" "number 6, value 1"\ #escape return
 "number 1, value -32767" "number 1, value 32767" #axevertical
do
#echo $GRAB
function joy()
{
jstest --event /dev/input/js0
} 
joy 1>grab2.txt
sleep 1 
PID=$(ps -e | grep jstest | cut -c 1-5) >/dev/null 2>&1 
sudo kill $PID 1>/dev/null
MATCH=$(grep -w "${GRAB}" grab2.txt | cut -c 32-) >/dev/null 2>&1
case $MATCH in 
"number 1, value -32767" ) xdotool key Up ;;
"number 1, value 32767" ) xdotool key Down ;;
"number 0, value -32767" ) xdotool key Left ;;
"number 0, value 32767" ) xdotool key Right ;;
"number 6, value 1" ) xdotool key Return  ;;
"number 4, value 1" ) xdotool key Escape ;;
esac
done
done
exit 0

