#!/bin/bash
# Version 0.7
#memo index  boutons start et select dans jstest ne pas decommenter
#START=8	
#SELECT=9
#memo index axes verticaux et horizontaux dans jstest  ne pas decommenter
#VERTICAL=5
#HORIZONTAL=4
#GRAB='number 4, value -32767'
#jstest --event /dev/input/js0 >grab.txt
while test $$ -gt 0
do 
for GRAB in "number 5, value -32767" "number 5, value 32767" \
"number 8, value 1" "number 9, value 1" "number 4, value -32767" \
"number 4, value 32767"
do
#echo $GRAB
function joy()
{
jstest --event /dev/input/js0 &
} 
joy > grab2.txt
sleep 1
PID=$(ps -e | grep jstest | cut -c 1-5) >/dev/null 
sudo kill $PID >/dev/null
MATCH=$(grep -w "${GRAB}" grab2.txt | cut -c 32-)
case $MATCH in 
"number 5, value -32767" ) xdotool key Up ;;
"number 5, value 32767" ) xdotool key Down ;;
"number 4, value -32767" ) xdotool key Left ;;
"number 4, value 32767" ) xdotool key Right ;;
"number 8, value 1" ) xdotool key Return  ;;
"number 9, value 1" ) xdotool key Escape ;;
esac
done
done
rm grab.tx grab2.txt
exit 0
